# Dependency Resolution Settings
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@dnd-mapp/*"
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 4320

# CLI Settings
engineStrict: true

# Build Settings
allowBuilds:
  "@parcel/watcher": false
  esbuild: false
  lmdb: false
  msgpackr-extract: false

# Other Settings
catalogMode: strict
savePrefix: "~"

# Catalogs
catalogs:
  angular:
    "@angular/build": ~22.1.6
    "@angular/cdk": ~22.1.4
    "@angular/cli": ~22.1.6
    "@angular/common": ~22.1.4
    "@angular/compiler-cli": ~22.1.4
    "@angular/core": ~22.1.4
    "@angular/platform-browser": ~22.1.4
    "@angular/router": ~22.1.4
    tslib: ~2.8.1
    typescript: ~6.0.3

  commitlint:
    "@commitlint/cli": ~21.2.2
    "@commitlint/config-conventional": ~21.2.2
    husky: ~9.1.7
    lint-staged: ~17.4.1

  eslint:
    "@angular-eslint/builder": ~22.1.0
    "@eslint/js": ~10.0.1
    angular-eslint: 22.1.0
    eslint: ~10.9.1
    eslint-config-prettier: ~10.1.8
    typescript-eslint: ~8.68.0

  markdown:
    markdownlint-cli2: ~0.23.2

  prettier:
    prettier: ~3.9.6
    prettier-plugin-organize-imports: ~4.3.0

  stylelint:
    stylelint: ~17.14.1
    stylelint-config-clean-order: ~10.0.0
    stylelint-config-standard-scss: ~17.0.0
    stylelint-order: ~8.1.1

  vitest:
    "@vitest/browser-playwright": ~4.1.11
    "@vitest/coverage-v8": ~4.1.11
    "@vitest/ui": ~4.1.11
    playwright: ~1.62.1
    vitest: ~4.1.11
